name: Build and Deploy to Amazon EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag \
          $ECR_REPOSITORY:${{ github.sha }} \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

                  - name: Push Docker Image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

      - name: Clone GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/charishma-1808/github-actions-eks-gitops.git

      - name: Update Deployment Image
        run: |
          cd github-actions-eks-gitops
          sed -i "s|image:.*|image: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}|g" deployment.yaml

      - name: Commit and Push Changes
        run: |
          cd github-actions-eks-gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add deployment.yaml
          git commit -m "Update image to ${{ github.sha }}" || echo "No changes"
          git push